### ISSUE TITLE
Instances (Examples) must have Ids

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#103]
IG publisher won't process an example instance that doesn't have an id. The id should be the same as the name of example, by default. FSH doesn't accept an Id: keywork on example instances. **Note:** This is an mCODE show-stopper.

**Comment by cmoesel** [comment]
More discussion on this here: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Instance.20generation/near/186185641

As noted, the intent, at one point, was to have the name serve as the _id_.  That intent got lost somewhere along the way (sorry).  For now, you can workaround by using the normal instance approach to setting an instance field:
```
* id = "MyID"
```

But we will fix it so that the _name_ is re-used as the `id`.

**Comment by markkramerus** [comment]
Implementing the workaround of adding IDs through rules.

**Comment by cmoesel** [comment]
Fixed in 0.6.1
