### ISSUE TITLE
Sub-extensions are incorrectly resolved to standalone extensions from FHIR and dependencies

### ISSUE THREAD

**Issue by jafeltra** [FHIR/sushi#1109]
When trying to resolve a sub-extension, SUSHI should first try to find a matching sub-extension by slicename before trying to fish for a match from FHIR and the other dependencies.

This issue was reported on Slack [here](https://mitrecorp.slack.com/archives/CSQV7N91A/p1654791467005609).

In the example where this was reported, this happens with an implied extension, but this may happen for any complex extension as well. The `location` slicename is incorrectly matching the `openEHR-location` extension.

**Comment by cmoesel** [comment]
After reviewing this more closely, this is not a bug; it is user error.  Upon further inspection, we found that the author was doing something like this:
```
* extension[http://hl7.org/fhir/5.0/StructureDefinition/extension-BodyStructure.includedStructure]
  * extension[location].valueCodeableConcept = SCT#78904004 "Chest wall structure (body structure)"
  * extension[qualifier].valueCodeableConcept = SCT#255503000 "Entire (qualifier value)"
```
The reason that `extension[location]` resolved to the `openEHR-location` and _not_ to an inline `location` sub-extension is that _there is no `location` inline sub-extension_.  If you look at [R5 BodyStructure.includedStructure](http://build.fhir.org/bodystructure.html), it's sub-elements are `structure`, `laterality`, and `qualifier`.  There is no `location`:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/2278253/183758530-15579aab-cf40-475e-9ea5-1a413e3322e3.png">

Since there is no `location` sub-element, SUSHI assumes that the author is referencing a standalone extension and attempts to resolve `location` against the id or name of a standalone extension (and succeeds, finding the openEHR location extension).  So, SUSHI is behaving as expected.

To fix this, the author needs to instead reference a valid existing sub-element.
