### ISSUE TITLE
Unhelpful advice when Instance name contains underscore

### ISSUE THREAD

**Issue by mint-thompson** [FHIR/sushi#1123]
Currently, when an Instance name contains underscores, SUSHI emits a warning message: `The string "My_Instance" represents a valid FHIR name but not a valid FHIR id. FHIR ids cannot contain "_" and can be at most 64 characters. The id will be exported as "My-Instance". Avoid this warning by specifying a valid id directly using the "Id" keyword.` However, the `Id` keyword cannot be used on Instances. Revise this message so that when this occurs on an Instance, they are advised to set the id using an assignment rule.

Zulip thread: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Instance.20names.20and.20underscores

**Comment by cmoesel** [comment]
Actually, in instances, the bit that comes after `Instance:` _is_ the id. That's why there is no `Id` keyword.  So the message is confusing and should be changed, but we should not direct the user to use an assignment rule either. I just tested this with FSH Online and confirmed that SUSHI _does_ change the id, so at least that part of the message is right.

How about something roughly like this?
> The string "My_Instance" is not a valid FHIR id. FHIR ids only allow ASCII letters (A-Z, a-z), numbers (0-9), hyphens (-), and dots (.). In addition, ids must be 64 characters or less. The id will be exported as "My-Instance". Avoid this warning by changing the Instance declaration to follow the FHIR id requirements.
