### ISSUE TITLE
The element or path you referenced does not exist: meta.lastUpdated

### ISSUE THREAD

**Issue by kyriosdata** [FHIR/sushi#1126]
The code below works fine in FSH Online (both directions) but fails on sushi (cli) with the error:
**The element or path you referenced does not exist: meta.lastUpdated**

```
Profile: SushiDefect
Parent: Patient
Id: ad169cce-0e5e-40f3-b21b-87f56d289d83
Title: "Sushi defect?"
Description: "This should work, but does not."
* ^meta.lastUpdated = "2020-09-20T21:02:10.935+00:00"
* ^version = "1.0"
```

**Comment by cmoesel** [comment]
Usually this happens if the FHIR cache is somehow corrupted.  Your FHIR cache is located at:
* Windows: `C:\Users\%USERNAME%\.fhir`
* Mac: `~/.fhir`

If you remove or rename the `.fhir` folder, then SUSHI will download the FHIR packages and rebuild the cache next time you run it.  This, however, will clear all FHIR packages from the cache.  If you want to try just removing the core FHIR package, you can delete the following folder instead (assuming you are using R4):
* Windows: `C:\Users\%USERNAME%\.fhir\packages\hl7.fhir.r4.core#4.0.1`
* Mac: `~/.fhir/packages/hl7.fhir.r4.core#4.0.1`

This issue (and solution) was recently discussed on chat.fhir.org here: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/.E2.9C.94.20Troubleshooting.20an.20Environmental.20Issue/near/289250073
