### ISSUE TITLE
SUSHI does not properly output exampleCanonical for examples whose meta.profile contains a version

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1138]
When SUSHI generates the IG JSON, it adds `exampleCanonical` for each instance that is an example of a profile in the IG.  This generally works, but if the example has a version appended in its `meta.profile` (e.g., `* meta.profile = "http://example.org/fhir/SomeProfile|1.0.0"`, then SUSHI fails to process it and uses `exampleBoolean` instead of `exampleCanonical`.

**Comment by mint-thompson** [comment]
When a version is provided in `meta.profile`, would the expected value for `exampleCanonical` be `http://example.org/fhir/SomeProfile` or `http://example.org/fhir/SomeProfile|1.0.0`?

**Comment by cmoesel** [comment]
I'd suggest the latter (w/ the version) -- but we should test w/ IG Publisher to make sure it works as expected.

**Comment by mint-thompson** [comment]
Ran a test with the IG publisher, and it looks like a versioned URL prevents an example Instance from being listed in the profile's list of examples. So, it might be best to leave out the version from `exampleCanonical`. This leads to another question: if `meta.profile` has a versioned URL, but it doesn't match the version we fish up, should we still use the URL for `exampleCanonical`, or should we just set `exampleBoolean` to `true`? I think that the latter is more correct, since a mismatched version may mean that the Instance doesn't actually conform to the profile the author thinks it conforms to.
