### ISSUE TITLE
Asterisk in markdown escaping backslash

### ISSUE THREAD

**Issue by jbyrdevans** [FHIR/sushi#1199]
When attempting to render an asterisk in a markdown field by using the escaped asterisk `\*`, the SUSHI compiler outputs `\\*` instead. See examples below:

*Example 1 FSH*
```
Instance: MyPlanDefinition1
InstanceOf: PlanDefinition
* status = #active
* description = """
\*something\*
"""
```

*Example 1 output*
```
{
  "resourceType": "PlanDefinition",
  "id": "MyPlanDefinition1",
  "status": "active",
  "description": "\\*something\\*"
}
```

*Example 2 FSH*
```
Instance: MyPlanDefinition2
InstanceOf: PlanDefinition
* status = #active
* description = "\*something\*"
```

*Example 2 output*
```
error Cannot find definition for Instance: "\*something\*". Skipping rule.
  Line: 13

{
  "resourceType": "PlanDefinition",
  "id": "MyPlanDefinition2",
  "status": "active"
}
```

**Comment by cmoesel** [comment]
Hi @jbyrdevans. You shouldn't need to escape `*` at all. If it's inside a string (using `"` or `"""` delimiters) it won't interfere w/ the `*` rule marker in the FSH syntax. Is there somewhere in the spec that implies you need to escape `*` in strings?

**Comment by jbyrdevans** [comment]
For markdown, an asterisk must be escaped in order render as an asterisk. Otherwise, it renders as bold/italics.

`*something*` renders as *something*
`\*something\*` renders as \*something\*

`**something**` renders as **something**
`\*\*something\*\*` renders as \*\*something\*\*

**Comment by jbyrdevans** [comment]
There's an easy work-around to use `&ast;` for an asterisk instead of `\*`, but I thought I'd raise the issue since the SUSHI compiler appears to be escaping the backslash instead of recognizing it as an escaped asterisk.

**Comment by cmoesel** [comment]
Oh... I see. You want to escape the `*` in MD so that MD doesn't treat it as bold or a bullet.  Sorry for my misunderstanding. I thought you were concerned about the `*` being misinterpreted by SUSHI. I get it now.

I think that what SUSHI is doing is actually correct. SUSHI produces JSON, and according to the JSON specification (most clearly stated in [ECMA-404](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) section 9), you _must_ escape the `\` character itself (since it is the escape character for other sequences).  In other words, a literal `\` in a JSON string must be represented in its escaped form as `\\`.

So when SUSHI outputs `"description": "\\*something\\*"`, the real value of `description` (after you JSON-decode it) is `\*something\*`. If that's causing problems somewhere, maybe there is another tool in the stack that is not properly deserializing JSON?
