### ISSUE TITLE
Slicing anomaly in instance of US Core Organization

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#121]
There something wrong with the attached example. 

[Organization-mCODEOrganizationExample01.json.txt](https://github.com/FHIR/sushi/files/4098514/Organization-mCODEOrganizationExample01.json.txt)

The IG Publisher complains that:

`Practitioner | error | Unrecognised property '@identifier:NPI'`

Here's the FSH - it is pretty straightforward:

```
Instance: mCODEOrganizationExample01
InstanceOf: USCoreOrganization
* id = "mCODEOrganizationExample01"
* identifier[NPI].value = "1265714091"
* active = true
* name = "Foundation Medicine"
* contact.telecom.system = #phone
* contact.telecom.value = "617-418-2200"
* address.line = "150 Second Street"
* address.city = "Cambridge"
* address.state = "MA"
* address.postalCode = "02141"
* address.country = "USA"
```

**Comment by markkramerus** [comment]
PS -- I added the .txt to the file name because a json file wasn't accepted.

**Comment by cmoesel** [comment]
Oh.  Yeah, that instance JSON is definitely wrong.  @ngfreiter -- looks like the slicename support in instance generation might not be quite working as expected...  Perhaps it works with FSH-defined profiles but not external profiles?

**Comment by markkramerus** [comment]
Here's another case with a different rendering. It comes from mCODECancerGeneticVariantExample01.json:
```
  "category:Laboratory": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/observation-category",
        "code": "laboratory"
      }
    ]
  },
```
The IG Publisher reports:
`Unrecognised property '@category:Laboratory'`

**Comment by ngfreiter** [comment]
It looks to me like the issue arises specifically when a slice element is fixed on a Structure Definition, and we then make an instance of that Structure Definition. The function that is supposed to set fixed values based on the Structure Definition does not handle the case of a slice element correctly.

**Comment by cmoesel** [comment]
Note that @jafeltra's work on another issue exposed this bug further.  Her work adds some validation where there previously was none.  As a result, these errors that used to fail silently are now logged.  The other result is that rather than putting the invalid properties into the JSON, they are now skipped.

These errors still exist and _are_ an error with SUSHI.  Now they're in the limelight being logged.  So when you run the next SUSHI release, don't be surprised by additional errors reported by SUSHI (and few errors reported by the IG Publisher).
