### ISSUE TITLE
Instances of Logical Model documentation doesn't work as written

### ISSUE THREAD

**Issue by awatson1978** [FHIR/sushi#1238]
Follow up to ticket #1232 

I just sat down to create a [minimal reproduction](https://github.com/clinical-meteor/logical-models-test) based on the existing documentation on [Instances of Logical Model](https://fshschool.org/docs/sushi/tips/#instances-of-logical-models).

Used the exact code that was written in the documentation, and from a newly initialized SUSHI IG.  Error that I'm receiving:

<img width="1396" alt="Screenshot 2023-03-12 at 3 38 08 PM" src="https://user-images.githubusercontent.com/675910/224572173-2565f4f7-1833-4c50-81cd-f4aa64f7d1fe.png">

**Comment by awatson1978** [comment]
@cmoesel

**Comment by jafeltra** [comment]
@awatson1978 I took a look at this because I was curious. I think the problem is due to the `exampleCanonical` on the Binary resource in the `resources` list in your `sushi-config.yaml` file. The `exampleCanonical` should point to the url of the logical model that the instance is an example of. You can determine the URL two ways. You can look it up directly by looking at the `url` property on the Logical Model (it is in `fsh-generated/resources/StructureDefinition-MyLM.json`). Alternatively, if you don't have the Structure Definition that SUSHI builds yet, you can figure it out yourself by using the canonical you have defined at the top of the `sushi-config.yaml` file as the base and appending `[Type]/[Id]` at the end of the canonical URL. For this example, this would be `https://github.com/clinical-meteor/logical-models-test/StructureDefinition/MyLM`.

I tried it, and updating the `exampleCanonical` lets the IG Publisher get through the full process and the example is listed in the Examples for your Logical Model when looking at the IG it builds.

If I missed something you were looking for, let me know!

**Comment by awatson1978** [comment]
Hey!  That did the track!  Amazing!  Thank you so much.  :)

**Comment by awatson1978** [comment]
I'm going to leave the other repository up so future people who need this can have a reference example.  Thanks for the help!

**Comment by jafeltra** [comment]
Glad to hear it!
