### ISSUE TITLE
FHIR R5 not available as an option in online playground

### ISSUE THREAD

**Issue by vadi2** [FHIR/sushi#1273]
R5 is not available as an option in https://fshschool.org/FSHOnline:

<img width="661" alt="image" src="https://github.com/FHIR/sushi/assets/110988/a6629688-5dc7-48d3-9760-b4b807f78774">

**Comment by vadi2** [comment]
R5 does seem to be used by default though, looking at the output:

```
info  Using FHIR Version 5.0.0
info  Loaded package hl7.fhir.r5.core#5.0.0
```

**Comment by cmoesel** [comment]
Hi @vadi2. The ability to select a FHIR version is a new feature of FSH Online. When we implemented it a few weeks ago, FHIR R5 was not yet available in the primary FHIR registry (it was only in package2.fhir.org, which doesn't support browser-based API calls). For this reason, we could not offer it as a choice.

Since then, the Simplifier team added support for R5 in the primary FHIR registry. We're working on adding it to FSH Online, but it's a little trickier because it's the first version of FHIR that does not include extensions in the core package -- so when we detect R5, we need to do some extra things we didn't need to do before!

You did stumble on an unintended "feature" however. If you load an R5 resource on the right-hand side and convert to FSH, FSH Online will read in its `fhirVersion` and attempt to use it (even if it's not a supported version of ours). After that, the unsupported version (R5) stays in the in-memory configuration until you reload the page or convert a non-R5 resource. So... what you're seeing is not intentional. It may be useful, but also is likely broken for certain cases.

BTW -- if you wish to report further issues against FSH Online in the future, you can report them directly against its repo here: https://github.com/FSHSchool/FSHOnline/issues

**Comment by vadi2** [comment]
Aha thanks, I knew the fshonline repo existed but could not find it under the FHIR organisation!

**Comment by cmoesel** [comment]
FSH Online now supports FHIR R5.
