### ISSUE TITLE
Warn when instances look like examples but omit "Usage: #example"?

### ISSUE THREAD

**Issue by jmandel** [FHIR/sushi#1303]
It seems somewhat common for developers to create example resources without adding

    Usage: #example 

There may be some heuristics that could help here, if the title/description says "example" but the usage does not.

**Comment by cmoesel** [comment]
In FSH, if the author does not specify a usage, it defaults to `#example` (see [Defining Instances](https://hl7.org/fhir/uv/shorthand/reference.html#defining-instances)) -- so omitting `Usage:` is actually an expected behavior. We try to have reasonable defaults (to help keep the "short" in "shorthand"), and since the vast majority of `Instance` definitions in an IG are usually examples, we made that the default.

It actually might be more helpful for us to warn when an Instance doesn't have `Usage:` and looks like a _conformance_ resource (e.g., a `SearchParameter`, `OperationDefinition`, or `CapabilityStatement`) -- since it's less likely that a conformance resource would be an example.
