### ISSUE TITLE
ignore .gitignore

### ISSUE THREAD

**Issue by litlfred** [FHIR/sushi#1458]
would be great it sushi automatically ignored .gitignore to avoid messages like:

>  debug File not processed by SUSHI: /Users/litlfred/space_cats/smart-trust/input/resources/.gitignore

**Comment by patrick-werner** [comment]
i think this is true for all .dotfiles?

**Comment by cmoesel** [comment]
SUSHI does ignore `.gitignore` files (and any other non-XML / non-JSON files). That's actually what that debug log is telling you -- SUSHI did not process it (i.e., it ignored it). We made the log message _debug_ level because we knew it wasn't something people would normally want to see, but we thought it could be helpful in some cases when troubleshooting unexpected results.

**Comment by litlfred** [comment]
Thanks for the response.  Somehow I didn't notice the 'debug' level.

Cheers,
-carl
