### ISSUE TITLE
Support i18n - Spanish, Portuguese

### ISSUE THREAD

**Issue by alejosv** [FHIR/sushi#1531]
Hi guys, thanks for this awesome tool, to LATAM beginning be a "indispensable tools". For this reason and beacause the mayor projects are publics exists the neccesary the official documentation must be published in spanish or portuguese.

I've search if SUSHI have a stable options to support i18n but I can't not founded, so I wonder really exists this options in SUSHI.

**Comment by cmoesel** [comment]
Hi @alejosv. SUSHI should support international characters in strings as long as the file is encoded using UTF-8. It will issue warnings if you use international characters in names (e.g., the name after `Profile:`, `Extension:`, `ValueSet:`, etc) because the FHIR spec says those `name` elements should be alphanumeric. But you should definitely be able to use international characters in strings for elements like `short`, `definition`, `description`, etc -- as well as putting international characters into markdown files.

Please let us know if you find that SUSHI is not behaving correctly with international characters.

**Comment by alejosv** [comment]
Thanks @cmoesel for your answer, but my question isn't about UTF-8 encoded and sorry If my explanation was not clear. When compile a IG all the template output in english and in countries in latinamerica (for example) have implementation guides in spanish and english mixed up like this:

![image](https://github.com/user-attachments/assets/84b4e6a5-009a-4e67-b58b-5a0f20fd1539)
![image](https://github.com/user-attachments/assets/7be88fec-913f-47a1-9a25-866b8951e3d0)
![image](https://github.com/user-attachments/assets/9e5ff520-065a-4f20-b9c1-cf5256de901b)

I've looking for in SUSHI documentations, but not found some reference about this.

**Comment by cmoesel** [comment]
Thank you for clarifying. The part of the process that uses templates to generate pages is handled by the IG Publisher. I would suggest that you reach out to Lloyd (@lmckenzi) and Jose (@costateixeira) about this -- as they are experts in the template system and I think also involved in i18n efforts. The best place to reach out is probably to post a question on the [#IG creation](https://chat.fhir.org/#narrow/channel/179252-IG-creation) channel in Zulip and tag Lloyd McKenzie and Jose Costa Teixeira.

**Comment by alejosv** [comment]
Great !!!
