### ISSUE TITLE
Extra cardinality in Diff ?

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#181]
If the one bound of the cardinality is changes, it seems the diff has both min and max elements and should only have the element that was actually changed.
This had a very bizarre affect on the generate snapshot of not displaying the element correct (for reasons unknown). See email in later comment...

**Comment by regelkraut** [comment]
Error Message from qa.html:

  | The  profile  http://hl7.at/fhir/AustrianPatient/StructureDefinition/austrian-patient  has 1 element in the differential (id:  Patient.extension:CS.extension:code.valueCodeableConcept) that don't  have a matching element in the snapshot: check that the path and  definitions are legal in the differential (including order)
-- | --

**Comment by cmoesel** [comment]
Hmm... Can you provide some FSH to reproduce this?  Last I checked, I thought we only produced the element for whatever card part changed (min or max) -- but maybe there are some edge cases where we're doing something different?

**Comment by regelkraut** [comment]
@cmoesel - Of course, here is the FSH we've used.
I've uploaded it as a TXT-File since github doesn't support the file type FSH (yet)
[AustrianPatient.txt](https://github.com/FHIR/sushi/files/4145816/AustrianPatient.txt)

the interesting lines in it are 28 & 29

**Comment by cmoesel** [comment]
Ah!  OK.  If it's the bit where we introduce the extension, I'm not surprised that we supply both the min and the max, because that's a brand new slice that did not exist in original base resource (that is being profiled).  But it sounds like we should actually be generating the diff based on the base element that has been sliced rather than the presence or not of the slice in the parent resource.  (Hopefully that last sentence made sense).  This is something I was considering last week but did not realize it had negative consequences.  We'll have to take a look at this.  Thanks again!

**Comment by markkramerus** [comment]
Part of the solution might be to allow one-sided cardinalities. For example, if the parent is 0..* and the child wants to constrain to 1..*, maybe the FSH statement should be `* element 1..` omitting the upper cardinality.

**Comment by cmoesel** [comment]
Maybe we could _allow_ that (`* element ..1`) but I wouldn't want to require it-- as I find that listing the full card in the FSH seems more user-friendly to me.  We should be able to figure it out on our end in the sushi.  I think this is just a case of what we're generating the diff against.
