### ISSUE TITLE
codeableconcept display are not being generated in 

### ISSUE THREAD

**Issue by Healthedata1** [FHIR/sushi#187]
- display text for CC not being generated for instances when defined e.g. for

~~~
 * extension[PA].extension[genderStatus].valueCodeableConcept = http://hl7.org/fhir/animal-genderstatus#unknown "Unknown"
~~~

  only get code and system....

see Zulip https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/SUSHI.20not.20setting.20.20coding.2Edisplay.20values/near/187224545

**Comment by cmoesel** [comment]
As discussed on Zulip, this is likely because we share code for fixing/patterning values in SDs and setting values in instances.  We need to revisit our approach there and decide:
* should we have separate syntax for `fix` and `pattern` to allow the _author_ to decide which mechanism to use? (currently SUSHI chooses for you based on the type)
* if the author puts a display on a fixed value in a profile/extension, should we propagate that to the SD even though it's generally not recommended to _require_ a certain display?

**Comment by cmoesel** [comment]
After discussion, we  propose #218 to allow to put control of `pattern[x]` vs `fixed[x]` in the hands of the author -- and allow with that, we will make it so that if the author includes a _display_ it will be put in the `pattern[x]`/`fixed[x]`.  This will also have the effect of including the _display_ in instances when the user indicates one -- addressing the original problem reported in this issue.

**Comment by cmoesel** [comment]
Will be fixed in next release of SUSHI
