### ISSUE TITLE
Can't add arbitrary extensions to example instances

### ISSUE THREAD

**Issue by Healthedata1** [FHIR/sushi#188]
An instance ( example) should be able to have any number of extensions even if they are not defined inline.   Right now an extension in an instance that not defined as part of the SD is causing the the instance not be generated.

**Comment by cmoesel** [comment]
Agreed.  The extension should not have to be specified in the profile in order to use it.  Thanks for the report.

The one potential caveat/issue is that if you reference an extension that is not in one of the declared package dependencies, SUSHI will not know anything about that extension -- so we'd either need to take the author's word for it (and generate it exactly as-specified in the FSH) or throw out an error since we can't process usages of unknown (to SUSHI) extensions.  But I think that's a slightly different issue.
