### ISSUE TITLE
Slices of type #value should be using fixedXXX instead of patternXXX

### ISSUE THREAD

**Issue by jduteau** [FHIR/sushi#314]
I have a slice of type #value and the generated profile sets the patternCode instead of fixedCode.  I think that a general rule for #value slices would be to use fixedCode.  Patterns only work for CodeableConcept, Coding, and Identifier.

**Comment by cmoesel** [comment]
If you have not seen it, please take a look at the details regarding the new fixed `(exactly)` capability in the [SUSHI 0.11.1 Release Notes](https://github.com/FHIR/sushi/releases/tag/v0.11.1). Rather than choose `fixed[x]` or `pattern[x]` for you, SUSHI now gives authors the power to choose (and a consistent approach for choosing). In your case, it sounds like you need to add `(exactly)` to the fixed value rules you want to use `fixed[x]`.

As for where patterns can and cannot be used, patterns are applicable to all FHIR data types.  Even for primitives there is a practical difference: a primitive fixed using `fixed[x]` cannot have an internal `id` or `extension`s, whereas a primitive fixed using `pattern[x]` _does_ allow for an internal `id` and `extension`s. Some FHIR experts recommend `pattern[x]` for nearly everything unless you have a very good reason for using `fixed[x]`.

Regarding the distinction between `#value` and `#pattern` discriminator types -- there was a [recent discussion on Zulip](https://chat.fhir.org/#narrow/stream/179280-fhir.2Finfrastructure-wg/topic/Is.20there.20a.20difference.20between.20value.20or.20pattern.20slicing.3F) on this topic, and it (somewhat surprisingly) concluded that the distinction is not meaningful and the two discriminator types should somehow be merged in a future version of FHIR (along with `#valueset`). But for FHIR R4, the distinction is meaningful, so authors should try to make sure their fixed value rules match the discriminator type they are using.

We can look into the possibility of having SUSHI issue an error when it detects that a `#value` binding has been used with a `pattern[x]` fixed value. I expect that is an error you would rather encounter earlier (in SUSHI) than later (in the FHIR IG Publisher).

**Comment by jduteau** [comment]
Yes, I fixed it (no pun intended) by adding the (exactly) keyword.  
I understand the distinction between the two, but the problem is that unless the type is CodeableConcept, Coding, or Identifier, the validator will error out (and subsequently the publisher will raise an error) if we specify patternX.  That's why I was suggesting that #value types should always be fixed.  But I'm fine with the (exactly) keyword.

**Comment by cmoesel** [comment]
I just read the [Zulip thread](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/New.20validation.20error.20.22Unsupported.20fixed.20pattern.20type.2E.2E.2E.22) and was surprised to see Lloyd's comment:

> Unsupported means that the publisher doesn't currently support handling patterns for ContactPoint. (The number of types supported is actually pretty small so far - Coding, CodeableConcept, and maybe one or two others.)

This isn't mentioned in any docs I've ever seen and, in fact, Lloyd was one of the vocal proponents of using `pattern[x]` on primitives, as far as I'm aware.  Hmmm...

**Comment by cmoesel** [comment]
It looks like the FHIR team is committed to adding more support for `pattern[x]` rather than require we (SUSHI/FSH) to change... Closing this issue since `(exactly)` fits the bill.
