### ISSUE TITLE
Annoying white space dependency

### ISSUE THREAD

**Issue by saulakravitz** [FHIR/sushi#318]
THis is OK:   Alias:   $OrgType = http://terminology.hl7.org/CodeSystem/organization-type

This is NOT:  Alias:   $OrgType= http://terminology.hl7.org/CodeSystem/organization-type

**Comment by cmoesel** [comment]
After discussion, we've decided to keep the grammar as-is, which requires spaces around the `=`.  In order to allow _no space_ around the `=`, we would need to make some changes to the grammar which would actually make FSH stricter than FHIR regarding what is not allowed in paths.  We don't feel that this was appropriate.  We also feel that enforcing some consistent style in FSH _can_ be a good thing -- and that's how we're choosing to look at this.

That said, we are updating SUSHI to produce more meaningful error messages -- so if an author does make a mistake like this, the error message will be extremely clear: `Alias declarations must include at least one space both before and after the '=' sign`.
