### ISSUE TITLE
SUSHI (probably) assumes that locally defined things have canonical-based URLs

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#380]
It's possible for someone to use `^url = ...` to override the URL for any profile, extension, value set, code system, etc.  But I think there are places in our code (Fisher?) that probably assume the generated URL for these instead of considering that it might be overridden.  We should look into this and fix it as appropriate.

**Comment by cmoesel** [comment]
For example, if you create a `CodeSystem` and override its URL -- then if you use the codesystem in a code (e.g., `MYCS#mycode`) -- will SUSHI use the overridden URL when generating the code or does it assume `${canonical}/CodeSystem/${codeSystemId}`?  Similarly, if you use it in a VS (e.g., `* codes from MYCS`) does it use the right URL?  This also applies to ValueSets, Profiles, Extensions -- anywhere that might have a `url` and the SUSHI might put the URL somewhere...

**Comment by mint-thompson** [comment]
After some investigation, I have determined the following:
* Overriding a url for a resource will produce the correct url on the exported FHIR resource.
* Referring to a locally defined `CodeSystem` with a rule that overrides its url will not produce the correct url in the location where the `CodeSystem` is referenced. This is because the url for the `CodeSystem` is found by fishing in the `FSHTank` for metadata. The `FSHTank` only deals with FSH types, and as such, the result it finds doesn't have its own `url` attribute, just a `CaretValueRule` that overrides the url. So, it is necessary for the `FSHTank` to inspect whatever it fishes up to see if it needs to override the usual generated url.
