### ISSUE TITLE
Problem w/ example: 1)Unrecognised property '@meta'   2)Inconsistency with IG

### ISSUE THREAD

**Issue by bwalsh** [FHIR/sushi#385]
## QA Error
![image](https://user-images.githubusercontent.com/47808/80136240-4c2e3600-8556-11ea-835c-fa0d42f559b7.png)

## Input

```
Profile:        DRSAttachment
Parent:         Attachment
Id:             drs-attachment
Title:          "DRS Attachment"
Description:    "An attachment with DRS Object attributes."
// https://github.com/ga4gh/data-repository-service-schemas/blob/master/openapi/data_repository_service.swagger.yaml#L190-L304

// adds DRSObject to Attachment
* extension contains DRSObject named drs 0..1

// remove hash from Attachment definition
* hash 0..0

// Make DRSObject MS
* extension[DRSObject] MS

Extension:  DRSObject
Id: drs-object
Title: "DRS Object"
Description: "The drs object"
* extension contains
    id 1..1 MS and
    name 0..* 

// inline definition of sub-extensions
* extension[id] ^short = "An identifier unique to this `DrsObject`."
* extension[id].value[x] only string
* extension[name] ^short = "A string that can be used to name a `DrsObject`."
* extension[name].value[x] only string


Instance: DRSAttachmentExample
InstanceOf: DRSAttachment
* extension[drs-object].extension[id].valueString = "any-id"
* extension[drs-object].extension[name].valueString = "any-file-name"

```

## Output
 build/input/examples/Attachment-DRSAttachmentExample.json

```
{
  "resourceType": "Attachment",
  "id": "DRSAttachmentExample",
  "meta": {
    "profile": [
      "http://theanvil.io/fhir/anvil/StructureDefinition/drs-attachment"
    ]
  },
  "extension": [
    {
      "extension": [
        {
          "url": "id",
          "valueString": "any-id"
        },
        {
          "url": "name",
          "valueString": "any-file-name"
        }
      ],
      "url": "http://theanvil.io/fhir/anvil/StructureDefinition/drs-object"
    }
  ]
}
```
As you can see, the meta tag QA is complaining about is present.

## IG

**However**, if we navigate to the IG artifact summary, we see this.  Note that meta tag is missing.

![image](https://user-images.githubusercontent.com/47808/80137681-7f71c480-8558-11ea-9963-76773db3bc6c.png)

**Comment by cmoesel** [comment]
Thanks for reporting this.  It seems this is happening because SUSHI always renders `meta.profile` to instances of profiles, but since `Attachment` is a _datatype_ (not a _resource_) it does not have a `meta` property.  I've never actually noticed that before -- so I guess it means that in FHIR there is no way to tag a datatype with a profile (except maybe if there is an extension to do that).

We need to fix this, but it may have other implications as I think we rely on `meta.profile` when generating the ImplementationGuide JSON file -- so we'll have to figure it out.

Please also be aware that this week we also found other cases where instances of datatypes don't behave the same as instances of resources.  For example, you can't assign an instance of a datatype as a property of another instance.  These are things we'll need to address in SUSHI.

**Comment by cmoesel** [comment]
As for `meta` not being in the example in the IG, this is because the HL7 FHIR IG Publisher strips out invalid elements from the JSON.

**Comment by bwalsh** [comment]
Thanks again for the quick response.

**Comment by bwalsh** [comment]
BTW, this jq snippet will remove the meta tag
```
 jq '{extension, id, resourceType}'   my-example.json
```

**Comment by ngfreiter** [comment]
This is related to #391. Since both these issues relate to the lack of support for creating inline instances of non-Resources. Once that is correctly supported, both of these issues should be solved.
