### ISSUE TITLE
Support markdown in Description

### ISSUE THREAD

**Issue by bkaney** [FHIR/sushi#414]
A really nice feature would be to support markdown for the value of `Description:`

**Comment by cmoesel** [comment]
If the target field in FHIR supports markdown, then any string should be rendered as markdown when the publisher processes it.  In other words, if you use markdown syntax in `Description:` it *should* work (since FHIR StructureDefinition `description` is a markdown type).  Is there something more specific you're looking for?  Or something more specific that isn't working as suspected?

**Comment by bkaney** [comment]
tl;dr This is not a sushi thing, I'll close this one.

The output ends as expected in the target `input/ImplementationGuild-xxx.json`. This is on the publishing side. I followed through java, then jekyll, and then to XSLT(!) to artifactSummary.xslt (around line 63). My XSLT(!) -foo has long left me, so I might have to punt on this.

**Comment by cmoesel** [comment]
Thanks for the update.  If it's something that can (or should) be fixed in the publisher or the IG template framework, you might want to report it in Jira and/or ask about it on Zulip.  Good sleuthing though!  XSLT.  Fun!
