### ISSUE TITLE
Conversion to base64 attachment.data

### ISSUE THREAD

**Issue by bkaney** [FHIR/sushi#415]
My use case: It would be really nice to be able to express CQL in plain text and have it base64 convert when building instance of a Library (e.g. `Library.content.data`)

**Comment by cmoesel** [comment]
I think this is a neat idea.  The trick would be how SUSHI knows if the string you put in the FSH is already encoded or if you want it encoded.

Probably the most explicit approach would be to introduce a keyword.  So something like:
```
* content.data = Base64("library ...")
```

Or we could introduce a new delimiter:
```
* content.data = %library ...%
```

Another approach would be to assume that if something is _not_ valid Base64 that we need to encode it and if it is valid Base64 to pass it on as-is -- but... that's not definitive and there could be edge cases where un-encoded strings are actually valid Base64 (e.g., 'abcd').  So that's probably not a viable approach...

**Comment by bkaney** [comment]
I like being explicit and intention revealing, e.g. a new keyword.

**Comment by cmoesel** [comment]
@markkramerus -- what do you think of this and is it something we can put into FSH for the 1.0 release or do we need to hold it for post-1.0?  I'm not sure if anyone commented on it -- and if not, if we can justify a post-ballot change without any comment to back it up.

**Comment by bkaney** [comment]
There is overlap here with binary adjunct file support in IG publisher (see https://confluence.hl7.org/plugins/servlet/mobile?contentId=66938614#content/view/66938614). Should sushi support the same `id` convention?

**Comment by cmoesel** [comment]
If I understand it correctly, the approach described in the documentation @bkaney linked to above should work with FSH and SUSHI today.  So if you set an `id` in your instance:
```
* content.data.id = "ig-loader-mylibrary.cql"
```
and then configure a path in `config.yaml`:
```yaml
parameters:
  path-binary: /path/to/ig/folder/w/binary/files
```
it should work.  I think the only potential gotcha is where that folder is.  If you want to put it in `ig-data`, it will have to go into one of the folders SUSHI copies over to the IG (currently, `input/{capabilities|examples|extensions|models|operations|profiles|resources|vocabulary}`).

**Comment by cmoesel** [comment]
Closing this issue as I believe the binary adjunct support in the IG Publisher solves the problem -- and SUSHI's new project format (that does not use `ig-data`) alleviates any confusion about where to put files.
