### ISSUE TITLE
sushi should check and handle missing array elements

### ISSUE THREAD

**Issue by DavidPyke** [FHIR/sushi#486]
In my haste, I deleted array element 1 and forgot to renumber 

parameter[0].targetProfile = "CEQSubscriptionBundle"
parameter[2].name = #return

This caused sushi to insert a null, resulting in an IG Publisher error 
Not a JSON Object: null (00:13.0946)

Array checking may be worthwhile to ensure that missing elements don't cause IG Publisher crashes.

**Comment by cmoesel** [comment]
The null value at index 1 is intentional, as SUSHI strives to do whatever the user tells it to do (and it's possible that the user might specify `parameter[1]` further down in the definition).  That said, your suggestion that SUSHI do some error checking is a good one.  If SUSHI emits a warning in this case, then at least the user has an opportunity to notice it before running the much more expensive IG Publisher process.  Thanks!
