### ISSUE TITLE
Alias in middle of files generates error

### ISSUE THREAD

**Issue by joepaquette** [FHIR/sushi#496]
Adding Alias: ... to top or bottom of file works with no Sushi error. The following generates an error:
`
ValueSet:       UspsTwoLetterAlphabeticCodes
Id:             us-core-usps-state
Title:          "USPS Two Letter Alphabetic Codes"
Description:    "This value set defines two letter USPS alphabetic codes."
Alias: USPS = https://www.usps.com

* USPS#ME "Maine"
* USPS#VT "Vermont"
* USPS#NH "New Hampshire"
* USPS#MA "Massachusetts"
* USPS#RI "Rhode Island"
* USPS#CT "Connecticut"
`

Error:
`
error extraneous input '*' expecting {<EOF>, KW_ALIAS, KW_PROFILE, KW_EXTENSION, KW_INSTANCE, KW_INVARIANT, KW_VALUESET, KW_CODESYSTEM, KW_RULESET, KW_MAPPING}
  File: /c/DevDays2020US/fsh-devdays-exercise-0.0.1/fsh/usps-state-codes-valueset.fsh
  Line: 7
`

**Comment by cmoesel** [comment]
Thanks for reporting this, @joepaquette.  This is by design -- `Alias` is allowed _between_ definitions (e.g., _between_ definitions for ValueSetA and ValueSetB) but it not allowed _in the middle_ of a definition.  In other words, once you start defining something (like a profile, extension, valueset), you can't define something else (like an alias) until you've finished defining the first thing.

We'll look at the language in the specification and try to clarify this, as you are not the first person who has tried this and tun into this error!
