### ISSUE TITLE
SUSHI should not require unnecessary config data when in `FSHOnly` mode

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#517]
In `FSHOnly` mode, the only _required_ config data is probably the `canonical` (which is needed to write the URLs for each resource).  SUSHI currently requires additional config properties that aren't even used for `FSHOnly`.  We should make it not require those other ones for `FSHOnly`.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Custom.20template.20folder/near/202727591

**Comment by mint-thompson** [comment]
I think `fhirVersion` might also be required, since that's necessary to load up FHIR and get a basic set of defintions. If `canonical` and `fhirVersion` are the only configuration attributes that are always required, then would it be fair to keep those in `MINIMAL_CONFIG_PROPERTIES` in `importConfiguration.ts`? `version` and `id` would then be moved to `IG_ONLY_PROPERTIES`.

**Comment by cmoesel** [comment]
Fixed in SUSHI 0.15.1
