### ISSUE TITLE
Setting Invariants adds parent constraints to differential

### ISSUE THREAD

**Issue by palfrey** [FHIR/sushi#562]
Using the following FSH:
```
Invariant: test-1
Description: "Limiting statuses"
Expression: "status=\"final\" or status=\"amended\""
Severity: #error

Profile: TestObservation
Parent: Observation
* obeys test-1
```

I expected `differential.element.constraint` for `TestObservation` to just contain `test-1`, but instead it also contains a bunch of `DomainResource` and `Observation` constraints (dom-2 to dom-6, obs-6 and obs-7). I've read over the FHIR spec bits about constraints and can't seem to isolate any reason for these?

**Comment by cmoesel** [comment]
Hmm... The `ElementDefinition.constraint` property is an array.  I don't think the FHIR spec is clear about how differentials work w/ arrays.  If a profile's parent has an element w/ property `foo: [a, b, c]` and the profile has differential element with `foo: [d]` -- is that supposed to be additive (e.g., `[a, b, c, d]` or is it supposed to replace the whole array (e.g., `[d]`)?  If it's supposed to be additive then that means there is no way to ever remove or replace something in an array.  If it's supposed to replace the whole array, then the differential needs to repeat any elements it wants to keep.

SUSHI takes the safe way out and repeats all the inherited elements when it adds to an existing array.  I call it the safe way out because it's the least harmful (as opposed to unknowingly clearing inherited values from the array).  BUT... is it necessary?  Maybe not?  Maybe FHIR assumes arrays are always additive because in a _constraining_ profile, it might always be illegal to remove existing elements from an array anyway?  I suppose it is worth asking a question on Zulip, which is what I will do.

**Comment by cmoesel** [comment]
Actually, I've just come up w/ a counter example in thinking this through.  `ElementDefinition.type` is an array.  In a differential, any `type`s you _don't_ include in the `type` array are interpreted as _profiled out_.  In other words, at least for the `type` property, the differential value is `replacing` not `additive`.  So if `constraints` is intended to be additive, then there must be special case logic/rules to allow for that difference.

**Comment by cmoesel** [comment]
https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Array.20values.20in.20differentials

**Comment by cmoesel** [comment]
SUSHI 1.2.0 now only outputs the _new_ `constraint` and `mapping` entries in `differential` elements.
