### ISSUE TITLE
Repeated elements in StructureDefinition with nested slices

### ISSUE THREAD

**Issue by mint-thompson** [FHIR/sushi#567]
The following FSH can be used as input to demonstrate the behavior:
```
Profile: PizzaBusiness
Parent: Practitioner
* extension contains TheBusiness named business 1..1
* extension[business].valueString contains badSlice 0..1
* extension[business].valueString[badSlice] = "The Bad Slice"

Extension: TheBusiness
* valueString ^slicing.discriminator.type = #value
* valueString contains goodSlice 0..1
* valueString[goodSlice] = "The Good Slice"
```

In the resulting StructureDefinition for `PizzaBusiness`, element.differential contains the following:
```
...
{
  "id": "Practitioner.extension:business.valueString:badSlice",
  "path": "Practitioner.extension.valueString",
  "min": 0,
  "max": "1"
},
{
  "id": "Practitioner.extension:business.valueString:badSlice",
  "path": "Practitioner.extension.valueString",
  "min": 0,
  "max": "1"
},
{
  "id": "Practitioner.extension:business.valueString:badSlice",
  "path": "Practitioner.extension.valueString",
  "min": 0,
  "max": "1",
  "patternString": "The Bad Slice"
}
```

**Comment by ngfreiter** [comment]
I think either way this is a bug, but I'm not sure the setup is really something that should be happening? Because `valueString` is not an array. So can we even slice that in the first place? I feel like somewhere an error should be thrown and we should say this is invalid...but I'm not sure where...hrmm.

**Comment by mint-thompson** [comment]
That's a really good point. I'll look more carefully at the FHIR docs for slicing, and I'll also see if I can recreate this behavior in SUSHI with list elements. Extensions are allowed to contain other extensions, so I'll start there.

**Comment by mint-thompson** [comment]
1. I tested out a similar case with nested extensions, and SUSHI produced output without any duplicate elements. That's good!
2. I went through https://www.hl7.org/fhir/profiling.html#slicing and https://www.hl7.org/fhir/elementdefinition.html#slicing a few times, and I can't find anything that would appear to explicitly disallow slicing on a `0..1` element. It's certainly an unusual thing to do, but as long as the [slice cardinality](https://www.hl7.org/fhir/profiling.html#slice-cardinality) rules are obeyed, it appears to be permitted by the spec.

**Comment by ngfreiter** [comment]
Oh yes that actually does make sense, because something like `valueQuantity` is really just value[x]:valueQuantity`, and `value[x]` is a `0..1` element, so there are definitely cases when you slice a non-array. When we address this bug, we should keep an eye out to see also if the bug is caused by the fact that the slicing is happening on `valueString`, since that is a choice element so it has its own special processing, and maybe that special processing is contributing to the bug.

**Comment by mint-thompson** [comment]
It looks like you were right: the problem does seem related to the fact that a choice element is being sliced. One consequence of this is the CardRule that is on the same line as the ContainsRule doesn't get applied, since the rule's path is `valueString[goodSlice]`, and the element we'd like to find with `findElementByPath` has path `Extension.value[x]`, sliceName `valueString/goodSlice`, and hence id `Extension.value[x]:valueString/goodSlice`.

Currently, when a matching slices is found in `StructureDefinition.findElementByPath`, the matching slice and its children are added to the `newMatchingElements` array. I think the solution will be to also add reslices of the matching slice, and children of those reslices, etc. to fully capture the set of elements that "start" with the matched slice.
