### ISSUE TITLE
Please add warning for unresolved references in examples

### ISSUE THREAD

**Issue by saulakravitz** [FHIR/sushi#568]
if you define:
field = Reference(InstanceName)
and InstanceName has not been defined, sushi remains very happy.

Please add a warning for unresolved references to short-circuit having to go through IG Builder to find these unresolved references.

**Comment by cmoesel** [comment]
We intentionally allow broken references in examples because authors may not want to fully flesh out every single thing an example refers to.  They may just want the one example and that's it.

Adding warnings seems reasonable, but still could be annoying for authors who really do just want to create the one example, even if it contains "dummy" references.  That said, if the IG Publisher squawks about dummy references, then we should consider emitting warnings in SUSHI as well.

**Comment by saulakravitz** [comment]
Any useful warning provided in sushi that saves a trip through the IG publisher saves at least 10 minutes.   
You can always make it an option to emit these types of warnings if the users are so sensitive.

**Comment by jafeltra** [comment]
#1468 was recently added and would log a warning in the example above. See #1155 for other similar, but slightly different, reference cases.
