### ISSUE TITLE
Sushi should warn/error when an invalid code in a locally defined CodeSystem is referenced

### ISSUE THREAD

**Issue by saulakravitz** [FHIR/sushi#595]
Currently, if an invalid code from a locally defined CodeSystem is referenced, no warning/error is generated in both Profiles and Examples.   Should generate an error in both, IMHO. Or at least a warning.

**Comment by cmoesel** [comment]
I realize this issue is a year old.  Sorry for the late response.  My only concern is that it might be confusing for SUSHI to do this type of validation in some cases (for local codes) but not for other cases (e.g., LOINC codes).  Do you think that might confuse authors?  If you got an error/warning about `MYCS#foo` being invalid, might you assume that since you got no error for `LOINC#bar` that it _is_ valid?

**Comment by saulakravitz** [comment]
1) The IG publisher is the final arbiter
2) Anything that Sushi can do to shorten the edit-compile-debug loop is a blessing to the developer.   Each time sushi flags a reference to a locally defined codesystem that is incorrect saves 5-10 minutes of time.   Definitely worth it IMHO.

**Comment by cmoesel** [comment]
Thanks for the feedback, @saulakravitz.  I'll add it to the backlog.  Can't say when it will get done, but it'll at least be on the list.
