### ISSUE TITLE
Fixed category in profile not inherited to instance

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#650]
The profile has a fixed value for the category, but the category value is entirely missing in the instance. 
See https://github.com/HL7/fhir-mCODE-ig/commit/9d2816c48b5efbff32cd6a2b961681f56888dc28

Run SUSHI and look at `Procedure-example1-mcode-cancer-related-radiation-procedure.json` and compare it to `StructureDefinition-mcode-cancer-related-radiation-procedure.json`.

**Comment by cmoesel** [comment]
This is because the profile indicates that `category` is `0..1`.  When SUSHI generates examples, it does not output any fixed/pattern values that have a lower card of `0` -- because they are, in fact, optional.  If it did, there would be no way for authors to generate an example _without_ it.

I'm sure that just raises a new question though: "Why is `category` `0..1` if the author has assigned a fixed/pattern value to it?"  I think I recall some past discussions on this -- and the conclusion that fixing a value does not imply that it is required.  It is valid to say "this value is optional, but if it is supplied, then it _must be X_."  If we automatically set the min to `1` then there is no way to say this (since any following card constraint to change it back to `0` would be seen as "widening" it).  So... you must also say `* category 1..1` to get the behavior you are looking for.

Does the spec indicate otherwise?

**Comment by markkramerus** [comment]
There is not concept of "instance inheriting from profile" in FHIR. But neither the FSH Spec and SUSHI documentation mention it, and they should.
