### ISSUE TITLE
Standalone extension description not copied to slice definition

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#655]
```
Extension: HistologyMorphologyBehavior
Id: mcode-histology-morphology-behavior
Title: "Histology-Morphology-Behavior"
Description: "An extension describing the morphologic and behavioral characteristics of the cancer."
```

```
extension contains  HistologyMorphologyBehavior named histologyMorphologyBehavior 0..1
```

Given the above, I would assume the description would be copied to the slice definition, but it is not:

![image](https://user-images.githubusercontent.com/492232/97510381-fa2df900-195a-11eb-92cf-7b8c948d94b2.png)

**Comment by cmoesel** [comment]
No, this is not something that SUSHI or the IG Publisher does.  The IG Publisher _will_ copy the `snapshot.element[0].short` from the extension definition to the extension use.  Have you tried setting the `snapshot.element[0].definition` in the standalone extension to see if the IG Publisher copies that over as well?  It could be.

If this is something you think SUSHI should support, we should consider what that means -- as it's outside of the behavior that has been defined, and we might want to see if there is an intentional reason the IG Publisher does not do it.  Given that it is duplicative data, and given what the IG Publisher already does with `short`, it seems more a thing that the IG publisher ought to do than SUSHI.

**Comment by cmoesel** [comment]
@markkramerus -- we discussed using `* . ^short = "..."` and `* . ^definition = "..."` in the extension definition to support this type of use case.  Is that solution sufficient?  If so, we will close this issue.  If not, let's discuss the requirements further.

**Comment by cmoesel** [comment]
SUSHI 1.1.0 now copies Extension `Title` and `Description` to the root element `short` and `definition` by default.
