### ISSUE TITLE
Feature to have sushi to run without any fsh file  ( sushi-config.yaml only option)

### ISSUE THREAD

**Issue by Healthedata1** [FHIR/sushi#672]
A feature to have sushi to run without any fsh file  ( sushi-config.yaml only option) would be handy for developers (like me) who only want to use the Sushi-config.yaml to create a ig resource and menu and not have worry about adding fsh files to the input folder and not have the ig-publisher automatically rerun sushi.

**Comment by cmoesel** [comment]
Currently, SUSHI can run without FSH _files_, but it seems it does require the `input/fsh` folder to at least _exist_.  So... a workaround would be to include an empty `input/fsh` folder.  But... if you're trying to avoid triggering the IG Publisher to run SUSHI (by _not_ having an `input/fsh` folder), then adding `input/fsh` would obviously defeat the purpose.

**Comment by Healthedata1** [comment]
I thought it would be nice feature but maybe others don't just use it
solely to manage the implementation guides.

Eric

Eric M Haas, DVM, MS
Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by cmoesel** [comment]
I think it is something we might be able to support.  I was just providing some additional information.

The tricky bit for us is that older versions of SUSHI supported projects without `input/fsh` or `fsh` folders -- so we need to be able to disambiguate between that legacy use case and a use case like yours (that should look in `input` for additional resources rather than `ig-data`).

**Comment by Healthedata1** [comment]
go it


Eric M Haas, DVM, MS
Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com
