### ISSUE TITLE
Caret syntax for value sets

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#691]
This is a feature suggestion that affects the FSH grammar as well as SUSHI implementation.
Right now, caret grammar cannot be used in value sets. My suggestion is that we allow access to top-level properties using caret grammar, as such:
```
* ^status = #draft
* ^experimental = true
```
and allow access to the properties of a particular `compose.include` like we do for ElementDefinition within StructureDefinition, e.g.:
```
* NCIT#C75533 "Fehlendes unerwünschtes Ereignis"
* NCIT#C75533 ^designation.language = de   // german
```
The code is treated like a path to the corresponding element of the `compose.include` array.

Admittedly, there is a gap in this proposal in terms of filter rules, but it still might be worth it to implement a partial solution.

**Comment by cmoesel** [comment]
I agree that it would be nice to support some of the other available properties in our formal grammar -- and I think that doing something _like_ the caret rule syntax for elements would offer some nice consistency.  How would this work w/ excluded codes?  E.g.:
```
* exclude NCIT#C75533 "Fehlendes unerwünschtes Ereignis"
* exclude NCIT#C75533 ^designation.language = #de   // german
```
would you repeat the `exclude` or not?  On one hand, it seems unnecessary, but on the other hand, for a casual reviewer, the lack of `exclude` in the caret rule might make it _look_ like it's being included.

As for `filter` rules, that's not a very large gap, as there are no "extra" properties we're missing in `filter` except the standard `id` and `extension` properties. So it's not quite as critical as `concept`, where we're missing `designation`.

Given that use of `designation` almost always carries two properties (`language` and `value`), however, this syntax means that the code is almost always repeated at least twice (not counting the initial declaration).  I wonder if perhaps something closer to the _`with` context_ proposal should be considered.  Then, instead of:
```
* NCIT#C75533 "Missing Adverse Event"
* NCIT#C75533 ^designation.language = #de   // german
* NCIT#C75533 ^designation.value = "Fehlendes unerwünschtes Ereignis"
```
You might have something like:
```
* with NCIT#C75533 "Missing Adverse Event"
** ^designation.language = #de   // german
** ^designation.value = "Fehlendes unerwünschtes Ereignis"
```
The prepended with feels a little weird there (especially if there was also an `exclude` operator.  So I'm wondering if maybe we should consider making `with` postfix?
```
* NCIT#C75533 "Missing Adverse Event" with
** ^designation.language = #de   // german
** ^designation.value = "Fehlendes unerwünschtes Ereignis"
```
(or you could argue that `with` is not needed at all since the next statements have `**`).

Anyway, some further things to think about.

**Comment by markkramerus** [comment]
` you could argue that with is not needed at all since the next statements have **`

This.

**Comment by cmoesel** [comment]
So you want us to pursue supporting something like this then?
```
* NCIT#C75533 "Missing Adverse Event"
** ^designation.language = #de   // german
** ^designation.value = "Fehlendes unerwünschtes Ereignis"
```

**Comment by markkramerus** [comment]
I think so, but later, after we have the multiple star thing worked out better.

**Comment by danka74** [comment]
There hasn't been any update on this issue for a while. Working with Swedish base profiles we also have the requirement to provide designations in Swedish. Any progress likely or are there alternative solutions for using languages in FSH? Happy to discuss requirements.
