### ISSUE TITLE
FHIR DSTU3

### ISSUE THREAD

**Issue by juanmcaputo** [FHIR/sushi#717]
Hi my name is Juan Manuel, and Im in a proyect wich involves FHIR DSTU3. And I want to use FHIR Shorthand to make the implementation Guide, the thing is that FHIR Shorthand only works with FHIR Version R4.
I now the best is to use FHIR R4, but for now it's impossible for my team to upgrade to this version, Is in the plans to extend the use to previus versions of FHIR, and Is there a way to bypass the prohibition of .yaml file to use STU3, and in this case Will I have  any problems with the diferences of the properties of the resources beetwen the FHIR Versions?

Thank you in advance.

**Comment by cmoesel** [comment]
Hi @juanmcaputo -- I apologize for the delayed response.  This issue somehow snuck by un-noticed.

As you noted, SUSHI supports only FHIR 4.x.  While you could edit the SUSHI code to allow it to accept FHIR STU3, there are several incompatibilities that would cause problems.  SUSHI is tightly tied to the definitions of `StructureDefinition`, `ElementDefinition`, `ValueSet`, and `CodeSystem`.  Since those were all made _Normative_ in R4, we can reasonably count on them not introducing incompatible changes in the _future_ -- but prior to R4 they did change with every release.  Here are a few of the changes from STU3 to R4 that would definitely cause problems for SUSHI:
* StructureDefinition: `contextType` replaced by `context.type` and `context.expression`
* ElementDefinition: `profile` and `targetProfile` changed from `0..1` to `0..*`
* ElementDefinition: `binding.valueSet[x]` renamed to `binding.valueSet` and changed from choice to non-choice

There are likely other smaller incompatibilities, but the change of cardinality for `profile` and `targetProfile` is actually a pretty big deal, as SUSHI deals with those fields a _lot_ throughout the code -- and the cardinality change affects the type (array vs non-array) and how you look for profiles (looping over `type` and `type.profile` vs looping over `type`).  In short, supporting STU3 would require significant refactoring in several sections of the code and _lots_ of testing -- while also making the code more difficult to maintain since you need to consider the two different possible representations of `StructureDefinition` and `ElementDefinition`.

**Comment by juanmcaputo** [comment]
Thank you for your reply, I think I'll edit the .html for this purpouse.

**Comment by cmoesel** [comment]
I'm not sure what you mean by that, but note that I only highlighted the differences in the core resources that SUSHI uses to _build_ FHIR profiles, extensions, etc.  There are many other more specific resources that changed from STU3 to R4 and those would affect the details of each profile produced.  To see what has changed from STU3 for any resource, you can look at the resource in R4 and click the "R3 Diff" tab.
<img width="475" alt="image" src="https://user-images.githubusercontent.com/2278253/106156605-bd3af380-614f-11eb-8d21-97f836ebbe7d.png">

**Comment by juanmcaputo** [comment]
@cmoesel  Thank you very much for your help!

**Comment by cmoesel** [comment]
Closing this issue as we have no plans for implementing support for FHIR STU3 in SUSHI.
