### ISSUE TITLE
Should be able to use indented insert rules 

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#828]
There may be a showstopper down the road somewhere, but it seems like I should be able to replace this:
```
* rest.resource[0]
  * interaction[0]
    * code = #read
    * extension[0].url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
    * extension[0].valueCode = #SHALL
   ```
with this:
```
RuleSet: SHALL
* extension[0].url = "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation"
* extension[0].valueCode = #SHALL

//snip

  * interaction[0]
    * code = #read
    * insert SHALL
```
Is there a reason this would not/should not be feasible?

**Comment by cmoesel** [comment]
Right now the reason is because there is no "long form" syntax for it.

When we originally proposed the indent syntax, we actually _did_ also suggest adding support for path-based inserts (e.g., `rest.resource[0].interaction[0] insert SHALL`) so that we _could_ do something like you suggest above.  But there was some confusion and we thought maybe we were introducing too many things at the same time -- so we scaled back and dropped the path-based inserts.

Personally I would like to see support for path-based inserts -- so I'm definitely game for picking them back up again.
