### ISSUE TITLE
Use of custom url in sushi-config.yaml

### ISSUE THREAD

**Issue by tanghaibao** [FHIR/sushi#848]
Dear,

I understand that the field `canonical` is supposed to be where you specify the link, and if I point to an arbitrary site (which I haven't set up yet), in `sushi-config.yaml`:

```
canonical: http://www.awesomefhir.org/fhir
```

sushi compiles fine but the publisher will sometimes timeout on this line:

```
Fetch http://www.awesomefhir.org/fhir/package-list.json for version check 
```

perhaps due to connection issues. I wonder if there is a way to turn off publisher checking for a remote `package-list.json` step?

Thanks!

**Comment by cmoesel** [comment]
That's a good question, but unfortunately, we (the SUSHI team) don't know the answer to that one!  I'd suggest posting this question on the [#IG creation](https://chat.fhir.org/#narrow/stream/179252-IG-creation) on Zulip.  Someone there may know the answer (since it is primarily related to the IG Publisher).
