### ISSUE TITLE
The instance example passes validation even the identifier doesn't match the rule

### ISSUE THREAD

**Issue by lindenquan** [FHIR/sushi#856]
In the below example, I want to add a rule to require a identifier with system  "https://my-system/identifier".  In the instance, I provided a wrong system "no-system" and expect sushi to show error messages saying "identifier with system https://my-system/identifier not provided". But the sushi shows all green, and the example passes the validation. 

Is the way I specify the rule incorrect ? or the sushi should show errors but it didn't ?

Thanks in advance
```
Profile: MyPatient
Parent: Patient
Id: my-patient
Title: "My Patient"
Description: "My Patient"

* identifier 1..*
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "system"
* identifier ^slicing.rules = #open
* identifier contains MyIdentifier 1..* MS
* identifier[MyIdentifier].system = "https://my-system/identifier" (exactly)

// Example instance that passes validation against this profile
Instance: patient
InstanceOf: MyPatient
Usage: #example

* identifier[0].system = "no-system"
```

**Comment by cmoesel** [comment]
SUSHI's primary purpose is to compile FHIR Shorthand, and while it does _some_ validation, it shouldn't really be considered a validator. Since validation happens when the IG Publisher runs (and/or is also available through other tools), we've chosen not to invest heavily in duplicating the features of other FHIR validators.

One thing that is particularly hard to validate is slice membership.  While the example above is fairly simple, other slice definitions can be much harder. So the reason SUSHI does not complain in your case is because it does not attempt to determine what slices are and are not present in the instance.  It leaves that validation to the IG Publisher.

Note that if you want to specifically identify slices in an instance (to take advantage of fixed values and limited validation of other constraints _within_ the slice, then you can index the slice by name (rather than using a numeric index).  For example, this _would_ produce an error because it would recognize that "no-system" is the wrong system for the MyIdentifier slice:
```
Instance: patient
InstanceOf: MyPatient
Usage: #example

* identifier[MyIdentifier].system = "no-system"
```

We recognize that it can be difficult to know what SUSHI will and won't validate and hope to address this via more specific documentation in the future.  We also may consider approaches that allow users to optionally invoke a Java-based validator when SUSHI completes.

**Comment by lindenquan** [comment]
Thanks very much. By using "identifier[MyIdentifier]", I'm able to get the errors. Thanks for your explanation. It makes sense to me that sushi decided to avoid duplicated effort on validation
