### ISSUE TITLE
Slicing on extension doesn't produce a proper differential

### ISSUE THREAD

**Issue by jduteau** [FHIR/sushi#871]
I have the following slice definition in a FSH file:
```
* careTeam MS
* careTeam.extension contains CareTeamClaimScope named careTeamClaimScope 1..1 MS
* careTeam.sequence MS
* careTeam.provider MS
* careTeam.provider only Reference(PASPractitioner or PASOrganization)
* careTeam.role MS
* careTeam ^slicing.discriminator.type = #value
* careTeam ^slicing.discriminator.path = "extension('http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-careTeamClaimScope').valueBoolean"
* careTeam ^slicing.rules = #open
* careTeam ^slicing.description = "Slice based on whether the care team member belongs to the overall claim or to an individual claim item."
* careTeam contains OverallClaimMember 0..14 and ItemClaimMember 0..10
```
This produces the following differential:
```
     {
        "id": "Claim.careTeam.extension",
        "path": "Claim.careTeam.extension",
        "slicing": {
          "discriminator": [
            {
              "type": "value",
              "path": "url"
            }
          ],
          "ordered": false,
          "rules": "open"
        },
        "min": 1
      },
      {
        "id": "Claim.careTeam.extension:careTeamClaimScope",
        "path": "Claim.careTeam.extension",
        "sliceName": "careTeamClaimScope",
        "min": 1,
        "max": "1",
        "type": [
          {
            "code": "Extension",
            "profile": [
              "http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-careTeamClaimScope"
            ]
          }
        ],
        "mustSupport": true
      },
      ...
        "id": "Claim.careTeam:OverallClaimMember",
        "path": "Claim.careTeam",
        "sliceName": "OverallClaimMember",
        "min": 0,
        "max": "14"
      },
      {
        "id": "Claim.careTeam:OverallClaimMember.extension:careTeamClaimScope",
        "path": "Claim.careTeam.extension",
        "sliceName": "careTeamClaimScope"
      },
```

That second declaration of the careTeam.extension causes the publisher validation code to fail because whenever it sees a path that ends in '.extension' with a sliceName, it assumes that there will be a type element as in the first declaration.

When I overrode the profile structuredefinition to include the type information, the publisher executed fine.

This *might* be a bug in the publisher FHIRPathEngine code, but it does seem like that that element in the differential isn't correct.

**Comment by cmoesel** [comment]
Hmm... interesting... IMO, the type should not be necessary, as the type should fallback (or inherit) from the base element being sliced. We've already declared the extension slice and its corresponding type. I do not know why we need to declare the type again. That said, this stuff is tricky, and perhaps the type is needed just to keep the tooling sane. Thanks for logging the bug -- hopefully the fix is not too difficult!

**Comment by julianxcarter** [comment]
It appears that [version 1.1.78 of the IG Publisher](https://github.com/HL7/fhir-ig-publisher/releases/tag/1.1.78) has addressed the bug that caused the publisher to crash during validation of the PAS project. As such I'm going to close this issue, since it no longer seems that sushi needs to be modified to comply. Thanks for logging this! @jduteau
