### ISSUE TITLE
SUSHI 2.0.0 Beta 2 allows illegal indentation

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#874]
The space counting is relative to the column where the first keyword is placed. So if `Profile:` starts in column 3, then everything that follows is evaluated as if column 3 were the left margin,

Example:
```
     RuleSet: NameRules
     * family MS
     * given MS

   Profile: MyPatientProfile
Parent: Patient
   * name 
     * insert NameRules
   * deceased[x] only boolean
  // More profile rules
```
This should really generate errors, but does not.

**Comment by cmoesel** [comment]
I believe that this is, to some degree, intentional.

Are you suggesting that:
1. the _last_ keyword should be used as the anchor for column 1 instead (rather than the first keyword)? OR
2. we should require consistent indentation across all keywords in a definition? OR
3. the whole concept of using keywords as the anchor for column 1 is wrong and first rules should always be on the true column 1?

Copying @ngfreiter since I think he was the one who proposed using keywords as the anchor for column 1.

**Comment by markkramerus** [comment]
The spec does not mention that column 0 is relative to the placement of the declaration. It says there should be no spaces before rules, or +2  spaces when indenting rules. Starting a rule in column 1, 3, 5 is a violation of the specification as it is currently written.  SUSHI could "forgive" this type of violation, just like browsers commonly forgive HTML errors, of course, but as a reference implementation, I don't know that it would be the best choice.

**Comment by ngfreiter** [comment]
I think [here](https://github.com/FHIR/sushi/pull/797#discussion_r615867283) we decided to indent relative to the first keyword. I have no problems with just being more strict and requiring rules to be on the first column. But we should decide that before doing an official SUSHI 2.0, since that could be a breaking change.

**Comment by mint-thompson** [comment]
A regression test using SUSHI's suite of regression-testing IGs showed that none of the IGs in the suite are trying to start an entity definition anywhere other than the leftmost column. Given this evidence, I think it is reasonable to update SUSHI to emit a warning when an author starts an entity definition somewhere other than the leftmost column.

**Comment by cmoesel** [comment]
@mint-thompson -- Was this against all the repos in `repos-all.txt`?  I find that `repos-all.txt` takes a very long time to run, so I'm asking since you submitted this comment only 30 minutes after our standup meeting ended -- and because I thought I remembered at least one repo indenting its definitions (although it's possible that they've fixed it since I last checked).

**Comment by mint-thompson** [comment]
@cmoesel No, this was with the smaller set. I'll run it with `repos-all.txt` now.

**Comment by mint-thompson** [comment]
Okay, so with the full set of repos, there were a few cases where there were indented entity definitions. In most cases, they appeared to be errors rather than formatting decisions. There was one repo, `hl7-eu/pcsp#master`, where there was some interesting and potentially useful formatting that had the entity's keywords indented 2 spaces and the rules indented 0 spaces. In all of these cases, these repos were also getting errors based on the entity keywords not being indented the same amount of spaces as the rules.

There were no cases where entities had all the lines of their definition indented the same amount, like we have in a lot of our test cases.

There were two repos I wasn't able to test. These repos have symlinks, which means that I get filesystem errors when trying to unzip the repo on my Windows machine. They were `HL7NZ/hpi#master` and `paulschneider/auto-ig-builder#master`.

**Comment by cmoesel** [comment]
Thanks, @mint-thompson!  Given that enforcing a 0-based indent only affects project/definitions where there are already indentation issues, it seems to me like this is a change we can make in SUSHI without negatively impacting any _otherwise working_ projects.  So, it sounds like we should (a) require the first rule to always be fully left-aligned, regardless of keyword indentation, (b) issue an error when we find otherwise.  The question is, should we still keep existing behavior (so it emits an error but still processes the code more-or-less correctly) or skip all rules that are not properly indented?
