### ISSUE TITLE
Rule Sets with Value Set Rules Generates errors

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#877]
Testing `insert` rules with value sets. SUSHI generates errors that indicate the RuleSet is being interpreted as a CodeSystem:
```
RuleSet: Hands
* $SCT#87683000  "Left handed (finding)"
```
Results in:
`error Do not include the system when listing concepts for a code system.`

https://fshschool.org/FSHOnline/#/share/3i4Mc5w

**Comment by cmoesel** [comment]
Implementing RuleSets is tricky when there are rules that have similar syntax but different requirements depending on where they are applied.  This is because when we parse the RuleSet into structured rules, we don't know which rule classes to use until we see where it is applied.  This seems to be what you've run into.  I've noted that it works correctly if you use the `include` keyword:
```
RuleSet: Hands
* include $SCT#87683000  "Left handed (finding)"
```

But... obviously we would want this to work correctly without it as well -- so we'll have to see what we can do.
