### ISSUE TITLE
Wrong defining URL in v2.0.0 beta 2

### ISSUE THREAD

**Issue by dragos-dobre** [FHIR/sushi#882]
When publishing with sushi v2.0.0 beta 2, all resources have as Defining URL as `/StructureDefinition/....` (different route) but the actual link is `/StructureDefinition-....` (same route). Ex. https://openimis.github.io/openimis_fhir_r4_ig/StructureDefinition-openimis-patient.html
This happens for all the FHIR elements. I had to manually update the ^url to match the generated url, but I think this should not be the case. Because of this, the IG Publisher gives validation errors: `Resource id/url mismatch:...`
Is this a configuration issue, sushi issue or IG Publisher issue? 
Github repo: https://github.com/openimis/openimis_fhir_r4_ig

**Comment by cmoesel** [comment]
By default, SUSHI constructs the defining URLs as `${igCanonicalURLBase}/${type}/${id}`.  This is the standard approach you will see in most IGs.  For example, the definining URL for [US Core Patient Profile](http://www.hl7.org/fhir/us/core/StructureDefinition-us-core-patient.html) is `http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient` even though the documentation is found at `http://www.hl7.org/fhir/us/core/StructureDefinition-us-core-patient.html`.  The defining URL and the documentation URL are not necessarily the same thing.

This is also the approach you see in the FHIR spec's discussion of canonical URLs [here](http://hl7.org/fhir/R4/references.html#canonical).  Note that while the spec says that the defining (canonical) URL _should_ resolve, it does not _require_ it.  In fact, the spec actually recommends using a registry to resolve the URL to a resource _before_ trying to just access the URL directly.  That said, when HL7 publishes IGs, it often creates special http redirects so that the defining URL redirects to the documentation if it is accessed directly.  This is also better because it allows the caller to specify a desired format (e.g., JSON or XML) rather than always getting the HTML.

As for the IG Publisher, I don't recall those specific errors, but you might want to ask about them on Zulip.
