### ISSUE TITLE
Sushi should check referential integrity of references

### ISSUE THREAD

**Issue by saulakravitz** [FHIR/sushi#968]
If a say Reference(x),  x should exist.
Currently, if it doesn't, sushi is happy, and the IG publisher throws an error.   
Annoying.

**Comment by cmoesel** [comment]
We intentionally allow for unresolvable references so that authors can create simple examples without having to author a full web of instances.  For example, If you only want to show how a CarePlan works, why should you also have to create a completely valid Patient just to satisfy the reference?  Some resources are even worse and would require 3 or 4 additional instances just to have "valid" references.

I don't think that IG Publisher always threw an error for unresolvable references (although I may be remembering wrong).   If it's doing that now, perhaps we should revisit this.

**Comment by saulakravitz** [comment]
The IG publisher error is for a broken link.
At the risk of suggesting more and more options, a mode where unresolved references are errors would be helpful.

**Comment by jafeltra** [comment]
#1468 was recently added and would log a warning in the example above. See #1155 for other similar, but slightly different, reference cases.
