### ISSUE TITLE
SUSHI does not support FHIR 5.0.0-snapshot1

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#994]
If you specify the `fhirVersion` as `5.0.0-snapshot1`, SUSHI will complain:
> The sushi-config.yaml must specify a supported version of FHIR. Be sure to add "fhirVersion: 4.0.1" (or 4.x.y, as appropriate) to the sushi-config.yaml file.

https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/R5.20support

**Comment by regelkraut** [comment]
Dear sender

due to a ransomware attack and necessary security measures, CGM is temporarily not reachable via the usual eMail addresses and Office phone numbers.
Please feel free to use SMS and mobile telephony to contact us.

Thank you for your understanding and best regards, your CGM Team

-----------------

Sehr geehrte Absenderin,
sehr geehrter Absender,

aufgrund einer Ransomware-Attacke und notwendiger Sicherheitsmaßnahmen, ist CGM vorübergehend nicht über die gewohnten eMail-Adressen und Festnetznummern erreichbar.
Bitte nutzen Sie gerne SMS und Mobilfunk-Telefonie, um mit uns Kontakt aufzunehmen.

Vielen Dank für Ihr Verständnis und freundliche Grüße, Ihr CGM-Team
